tap "beeftornado/rmtree"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "sanemat/font"
brew "carthage"
brew "cask"
brew "docker"
brew "docker-compose"
brew "git"
brew "mas"
brew "pyenv"
brew "tree"
brew "zsh"
brew "heroku/brew/heroku"
brew "sanemat/font/ricty", args: ["with-powerline"]
cask "alfred"
cask "alt-tab"
cask "appcleaner"
cask "clip-studio-paint"
cask "clipy"
cask "cmd-eikana"
cask "cyberduck"
cask "discord"
cask "docker"
cask "gimp"
cask "google-chrome"
cask "imageoptim"
cask "intel-power-gadget"
cask "iterm2"
cask "kindle"
cask "loopback"
cask "obs"
cask "sip"
cask "sketch"
cask "sketch-toolbox"
cask "sourcetree"
cask "visual-studio-code"
cask "wacom-tablet"
mas "Bear", id: 1091189122
mas "CotEditor", id: 1024640650
mas "Keynote", id: 409183694
mas "Magnet", id: 441258766
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "RunCat", id: 1429033973
mas "The Unarchiver", id: 425424353
mas "VirusBarrier Scanner", id: 1200445649
mas "Xcode", id: 497799835
mas "Yoink", id: 457622435
