tap "homebrew/bundle"
brew "docker"
brew "mas"
brew "tree"
cask "brave-browser"
cask "clipy"
cask "cmd-eikana"
cask "discord"
cask "google-chrome"
cask "google-drive"
cask "obsidian"
cask "visual-studio-code"
mas "Bitwarden", id: 1352778147
mas "CotEditor", id: 1024640650
mas "Magnet", id: 441258766
