# Reference:
# - [ようこそdotfilesの世界へ \#Vim - Qiita](https://qiita.com/yutkat/items/c6c7584d9795799ee164)
# - [dotfilesのすゝめ | kouki’s blog](https://blog.kmdkuk.com/2022/07/16/dotfilesのすゝめ.html)
# - [GitHub Actionsを使って、自分用にカスタムしたArch LinuxのISOイメージを作る](https://zenn.dev/inkohx/articles/3dbe67c0db1322)
# - [コンテナ内でのジョブの実行 - GitHub Docs](https://docs.github.com/ja/actions/using-jobs/running-jobs-in-a-container)
name: CI

on: push

jobs:
  setup-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotfiles
        run: bash setup/linux/setup.sh

  setup-ubuntu-plane:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    steps:
      - name: Install sudo
        run: |
          apt-get update && apt-get upgrade -y
          apt-get install -y sudo
      - name: Install required packages
        run: |
          sudo apt-get update && sudo apt-get upgrade -y
          sudo apt-get install -y curl git
      - name: Setup dotfiles
        run: curl -fsSL https://raw.githubusercontent.com/kem198/dotfiles/main/setup/linux/setup.sh | bash

  setup-archlinux:
    runs-on: ubuntu-latest
    container: archlinux:base
    steps:
      - name: Install sudo
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm sudo
      - name: Install required packages
        run: |
          sudo pacman -Syu --noconfirm
          sudo pacman -S --noconfirm curl git
      - name: Setup dotfiles
        run: curl -fsSL https://raw.githubusercontent.com/kem198/dotfiles/main/setup/linux/setup.sh | bash
